json:{
  "change_justification": "original",
  "extra_css": "div.figure,div.note{margin:1em 0!important}@font-face{font-family:literata-import;src:url(https://fonts.googleapis.com/css2?family=Literata:opsz@7..72&display=swap)}body,body.calibre{font-smooth:auto;text-shadow:0 0 4px rgba(0,0,0,.4);text-rendering:auto;-webkit-font-smoothing:antialiased;padding:1em;font-family:literata-import,serif!important}body>div{padding:0!important}body>p{max-width:90%!important}p{margin-bottom:1em!important;text-indent:0!important}div.note{padding:1em!important}div.list{margin:1em!important}",
  "base_font_size": 0.0,
  "font_size_mapping": null,
  "line_height": 0.0,
  "minimum_line_height": 120.0,
  "embed_font_family": "Literata",
  "embed_all_fonts": true,
  "subset_embedded_fonts": true,
  "smarten_punctuation": true,
  "unsmarten_punctuation": false,
  "disable_font_rescaling": false,
  "insert_blank_line": true,
  "remove_paragraph_spacing": false,
  "remove_paragraph_spacing_indent_size": 1.5,
  "insert_blank_line_size": 0.5,
  "input_encoding": null,
  "filter_css": ",color,background,font-family,background-color",
  "expand_css": false,
  "asciiize": false,
  "keep_ligatures": true,
  "linearize_tables": false,
  "transform_css_rules": "[]",
  "transform_html_rules": "[]"
}